import Head from 'next/head'
import Image from 'next/image'
import WhoWeAre from '../src/components/WhoWeAre/WhoWeAre'
import AboutUs from '../src/components/AboutUs/AboutUs'
import Alternative from '../src/components/Alternative/Alternative'
import BeCoopCycle from '../src/components/BeCoopCycle/BeCoopCycle'
import Footer from '../src/components/Footer'
import Hero from '../src/components/Hero'
import SideBar from '../src/components/SideBar'
import styles from '../styles/Home.module.css'
import ContactUs from '../src/components/ContactUs/ContactUs'

export default function Home() {
  return (
    <>
      <div className='homeBox'>
        <Head>
          <title>CoopCycle Web</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main >
          <SideBar />
          <Hero />
          <AboutUs />
          <BeCoopCycle />
          <Alternative />
          <WhoWeAre />
          <ContactUs />
        </main>
        <Footer />
      </div>
      <style jsx>
        {`
          .homeBox{
            min-height: 200vh;
          }
        `}
      </style>
    </>
  )
}
